name: ComandosDeComunicacion
main: muriplz.lel.ComandoMensaje
version: 2.5
load: POSTWORLD
api-version: 1.17
author: muriplz
commands:
  m:
    description: manda un mensaje a un jugador.
    aliases: message
  r:
    description: manda un mensaje al último jugador que te susurró.
    aliases: reply