name: Whisperoo
main: com.kryeit.Whisperoo
version: 1.0
load: POSTWORLD
api-version: 1.18
author: muriplz
softdepend: [AFKPlus]
commands:
  m:
    permission: whiperoo.message
    description: sends a message to a player.
    aliases: message
  r:
    permission: whisperoo.reply
    description: send a message to the player that last whispered you.
    aliases: reply