name: Gradle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew shadowJar
    - name: Export the builded project as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: Whisperoo-Dev
        path: build/libs/
